# Generated by Django 4.0.4 on 2022-04-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='validate_request',
            field=models.BooleanField(default=False),
        ),
    ]
